name: Build and Release apk
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.5"
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build apk
      - name: Push APK to Releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: build/app/outputs/flutter-apk/*,build/ios/iphoneos/app.ipa,build/app/outputs/bundle/release/app-release.aab
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "Upload binaries to release"
