name: Build and Release apk
on: push
jobs:
  build:
    name: Build APK
    env:
      my_secret: "${{secrets.GH_TOKEN}}"
      my_tag: "v1.0.${{github.run_number}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.5"
      - run: flutter pub get
      #- run: flutter test
      - run: flutter build apk
      - name: Push APK to Releases
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ env.my_secret }}
          tag: ${{ env.my_tag }}
          name: My Creative Name
          body: >
            This release actually changes the fabric of the reality, so be careful 
            while applying, as error in database migration, can irrecoverably wipe 
            some laws of physics.
          gzip: folders
          files: >
            build/app/outputs/flutter-apk/
