on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    env:
      my_tag: "v1.0.${{github.run_number}}"
    runs-on: ubuntu-latest
    steps:
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ env.my_tag }}
